### ISSUE TITLE
Weird colors on the header

### ISSUE THREAD

**Issue by pixelastic** [algolia/algolia.github.io#10]
![image](https://cloud.githubusercontent.com/assets/283419/22470715/724c82f0-e7d0-11e6-9c79-6d9deb936284.png)

![image](https://cloud.githubusercontent.com/assets/283419/22470705/6c281ac4-e7d0-11e6-8b4c-1d7fc8125639.png)

I had never realized it before (so maybe it's new), but the background color on each side of the header is not the exact same as the one of the header.

**Comment by LukyVj** [comment]
Not new.. :( 
Will be fix during the redesign!

**Comment by JonasBa** [comment]
Closing this in favour of the new design coming soon
