### ISSUE TITLE
add a link to the forum

### ISSUE THREAD

**Issue by Haroenv** [algolia/algolia.github.io#11]
see https://github.com/algolia/discourse/issues/29

> See this [forum thread](https://discourse.algolia.com/t/link-to-the-forum-on-algolia-community-page/637).
> 
> Could we add a link from somewhere (maybe the header) to community.algolia.com and also algolia.com? Visually I don't know the best way to propose this, open to ideas @JonasBa :)

@dzello

**Comment by LukyVj** [comment]
@Shipow Is it planned on the redesign ?

**Comment by dzello** [comment]
The redesign does have a big link to the forum but I would love to get one on the current site too. I keep putting off doing a PR for this /o\

**Comment by dzello** [comment]
@Haroenv Thanks for cross-linking over here. The title in that issue is misleading, it's actually about a link from discourse -> community. I will change it.

**Comment by JonasBa** [comment]
We have added one in the new design @Haroenv @dzello  👍
