### ISSUE TITLE
JavaScript not working on old browser

### ISSUE THREAD

**Issue by pixelastic** [algolia/algolia.github.io#119]
Seems like the JS of the page is not working on old browser, as per this bug report: https://github.com/algolia/jekyll-algolia/issues/57

Seems like it's failing on iOS 9 (and conkeror?). I don't have the devices to tests.

I don't know if we should fix this or not, I have no idea how old those browsers are. I think we should have at least the same compatibility that what we have to the instantsearch.js library.

**Comment by vvo** [comment]
We support latest browsers minus two versions (so iOS 10 and 11)

**Comment by vvo** [comment]
You can test the support on saucelabs.com, it's free and you can do a manual test

**Comment by pixelastic** [comment]
Ok thanks, so expected to fail on iOS9.
