### ISSUE TITLE
Magento Extension page UI bug

### ISSUE THREAD

**Issue by thekar22** [algolia/algolia.github.io#19]
Repro:
Go to this link: https://community.algolia.com/magento/doc/m1/getting-started/

Expected: No broken images

Observed:
![image](https://cloud.githubusercontent.com/assets/1109428/26737082/7d12375e-477d-11e7-8eb0-08b1a1cf4453.png)

**Comment by JonasBa** [comment]
Thanks Kyle :) I'm deploying a fix right now :)!
