### ISSUE TITLE
Header is crowded on mobile

### ISSUE THREAD

**Issue by dzello** [algolia/algolia.github.io#20]
Thoughts on how we should fix? cc @JonasBa 

<img width="391" alt="screenshot 2017-06-02 11 50 57" src="https://cloud.githubusercontent.com/assets/174777/26740289/c5ec543a-4789-11e7-91e8-ff211c8ffc0b.png">

**Comment by dzello** [comment]
Also I noticed the line break looks funny here, with source on it's own line. Maybe we can think of a fix for that too

**Comment by JonasBa** [comment]
Fixed ;)
