### ISSUE TITLE
Re-work categories

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algolia.github.io#27]
Here are the current categories:

- API Client 
- Library
- Live
- Plugin
- Tool
- Misc

I think we should / we could come up with more explicit names.

Here are a few suggestions:

**API Client & Library => Libraries**
I think it is not necessary to separate the 2 concepts. In the end they are both libraries.
Also, the moment we have faceting on the language, we would always yield only one result for API Client which would be weird.
Also this would solve the issue of wrongly classifying Framework integrations into the API Client category.

**Live => Live demos || Live examples || Demos**
I don't know what "live" alone means.

**Plugin => Integrations**
It looks like "Integrations" is the more abstracted way to define plugin/module/extension/bundle/whatever.

**Tool => Projects**
The current list of "tools" are really more "projects using Algolia".

**Misc => /dev/null **
I feel we should not have a "catch all" but rather make other categories more explicit.
Not sure where the Swag thing could fit in.

Other remarks:
- expectJSX should go to Libraries.
- GitHub awesome autocomplete should go to "projects"

I hope these comments make sense  @dzello , let me know what you think.

**Comment by bobylito** [comment]
There are some pretty good ideas here:
 - integration is the word we use for integrations :)
 - Tool is only good for tools, agreed that it might need to be renamed (projects seem good yes)

To be honest, I'm not sure about even promoting the API clients :trollface: (not really kidding though as they documented and they don't have their own websites).

Also I like misc. but it's true that if we had an actual category that would be better.

**Comment by dzello** [comment]
Great suggestions / ideas here. Going to think about it and comment back.

**Comment by vvo** [comment]
I did some changes, have a look. If you need more changes it's actually super easy to update the index.
