### ISSUE TITLE
Client feedback

### ISSUE THREAD

**Issue by vvo** [algolia/algolia.github.io#4]
Very good feedback from @gduvaux about the community page:

> instantsearch.js and the helper.js are the biggest areas.
> 
> It confuses potential clients because they ask _"Should I use instantsearch.js or helper.js? What are the differences between them? What about autocomplete.js"_ and the page is not able to answer that, nor the projects.

The answer to that could be **"We promote first instantsearch.js and autocomplete.js as the two main UI libraries of Algolia"**

To solve this, we though about:
- make instantsearch.js and autocomplete.js the two most important areas
- make the two areas of equal size
- add "UI LIBRARY" label instead of "LIBRARY"
- swap magento and helper.js areas (so magento gets bigger)
- change helper library to "code" to make it more obvious its not a full blown UI library

What do you think?

**Comment by gduvaux** [comment]
I love the idea... +1

**Comment by vvo** [comment]
Also see https://github.com/algolia/algoliasearch-helper-js/pull/291

**Comment by redox** [comment]
:+1:
