### ISSUE TITLE
Bug with places icon

### ISSUE THREAD

**Issue by LukyVj** [algolia/algolia.github.io#5]
![](https://puu.sh/qEvnf/de7162753d.png)

**Comment by bobylito** [comment]
Is it about the small glitchy triangle at the bottom of the pin?

**Comment by LukyVj** [comment]
Exactly

**Comment by LukyVj** [comment]
It shouldn't occurs

**Comment by Shipow** [comment]
fixed

**Comment by LukyVj** [comment]
U DA BEST
